config/routes.rb
Rails.application.routes.draw do
  root :to => "groups#index"
  resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base

	validates :title, :presence => true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.all
	end

	def show
		@group = Group.find(params[:id])
	end

	def new
		@group = Group.new
	end

	def edit
		@group = Group.find(params[:id])
	end

	def update
		@group = Group.find(params[:id])

		if @group.update(group_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end

	def create
		@group = Group.new(group_params)
		if @group.save
			redirect_to groups_path
		else
			render :new
		end
	end

	def destroy
	    @group = Group.find(params[:id])
	    @group.destroy
	    redirect_to groups_path
	end

	private 
	def	group_params
		params.require(:group).permit(:title, :description)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def welcome
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/groups/edit.html.erb
<divclass="span12">
	<%= simple_form_for @group do |f| %>
	<%= f.input :title, :input_html => { :class => "input-xxlarge"} %>
	<%= f.input :description, :input_html => { :class => "input-xxlarge"} %>
	<div class="form-actions">
		<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary"%> 
	</div>
<% end %> </div>

app/views/groups/index.html.erb
<div class="span12">
	<div class="group">
		<%= link_to("New group", new_group_path , :class=> "btn btn-mini btn-primary pull-right") %>
	</div>
	<table class="table">
		<thread>
			<tr>
				<td> # </td>
				<td> Title </td>
				<td> Description </td>
			</tr>
		</thread>

		<tbody>
			<% @groups.each do |group|%>
			<tr>
				<td> # </td>
				<td> <%= link_to(group.title, group_path(group)) %> </td>
				<td> <%= group.description %> </td>
				<td> <%= link_to("Edit", edit_group_path(group), :class => "btn btn-mini" ) %>
					<%= link_to("Delete", group_path(group), :class => "btn btn-mini", :method => :delete, :confirm => "Are you sure?" ) %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>	

app/views/groups/new.html.erb
<div class= "span12">
	<%= simple_form_for @group do |f| %>
		<%= f.input :title, :input_html => { :class => "input-xxlarge" } %>
		<%= f.input :description, :input_html => { :class => "input-xxlarge" } %>

	<div class="form-actions">
		<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
	</div>
	<% end %>
</div>

app/views/groups/show.html.erb
<div class = "span12">
	<div class = "group">
		<%= link_to("Edit", edit_group_path(@group) , :class => "btn btn-mini btn-primary pull-right") %>
	</div>
	<h2> <%= @group.title %> </h2>
	<p> <%= @group.description %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groupmy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
Hello World!!